[deps]
ACE1x = "5cc4c08c-8782-4a30-af6d-550b302e9707"
ACEfit = "ad31a8ef-59f5-4a01-b543-a85c2f73e95c"
ACEpotentials = "3b96b61c-0fcc-4693-95ed-1ef9f35fcc53"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
